const SET_PEOPLE_WANTED = "SET_PEOPLE_WANTED";
const SET_MIN_AGE = "SET_MIN_AGE";
const SET_MAX_AGE = "SET_MAX_AGE";
const SET_LANGUAGES = "SET_LANGUAGES";
const SET_DATE_START = "SET_DATE_START";
const SET_CITY = "SET_CITY";
const SET_CATEGORIES = "SET_CATEGORIES";
const SET_ALL = "SET_ALL";
const RESET_ALL = "RESET_ALL";

// DELETE TYPES
const DELETE_CATEGORY = "DELETE_CATEGORY";
const DELETE_LANGUAGE = "DELETE_LANGUAGE";
const DELETE_MIN_AGE = "DELETE_MIN_AGE";
const DELETE_MAX_AGE = "DELETE_MAX_AGE";
const DELETE_PEOPLE_WANTED = 'DELETE_PEOPLE_WANTED';

export default {
	SET_PEOPLE_WANTED,
	SET_MIN_AGE,
	SET_MAX_AGE,
	SET_LANGUAGES,
	SET_DATE_START,
	SET_CITY,
	SET_CATEGORIES,
	SET_ALL,
	RESET_ALL,
	DELETE_MIN_AGE,
	DELETE_MAX_AGE,
	DELETE_CATEGORY,
	DELETE_LANGUAGE,
	DELETE_PEOPLE_WANTED
}