const ADD_TO_FEED = "ADD_TO_FEED";
const SAVE_MAP_FEED = "SAVE_MAP_FEED";
const SAVE_MAP_CENTER = "SAVE_MAP_CENTER";
const SET_PAGE = "SET_PAGE";
const SET_NEXT_PAGE = "SET_NEXT_PAGE";
const SET_IS_LOADING = "SET_IS_LOADING";
const SET_IS_FILTERED = "SET_IS_FILTERED";
const SET_NEW_EVENTS = "SET_NEW_EVENTS";
const RESET_DATA = "RESET_DATA";

export default {
	ADD_TO_FEED,
	SAVE_MAP_FEED,
	SAVE_MAP_CENTER,
	SET_PAGE,
	SET_NEXT_PAGE,
	SET_IS_LOADING,
	SET_IS_FILTERED,
	SET_NEW_EVENTS,
	RESET_DATA
}