 const TOGGLE_BURGER_MENU = "TOGGLE_BURGER_MENU";
 const TOGGLE_MODAL = "TOGGLE_MODAL";
 const TOGGLE_ALERT = "TOGGLE_ALERT";


export default {
    TOGGLE_BURGER_MENU,
    TOGGLE_MODAL,
    TOGGLE_ALERT
}
