const TOGGLE_IS_AUTH = "TOGGLE_IS_AUTH";
const DATA_USER = "DATA_USER";
const TOKEN = "TOKEN";
const SET_EVENTS = "SET_EVENTS";
const IS_SUBMIT_CLICK = "IS_SUBMIT_CLICK";
const IS_CHANGE_USER_OPEN="IS_CHANGE_USER_OPEN";
const IS_PHOTOREDACTOR_OPEN = "IS_PHOTOREDACTOR_OPEN";
const SUBSCRIBE_EVENT = "SUBSCRIBE_EVENT";
const UN_SUBSCRIBE_EVENT = "UN_SUBSCRIBE_EVENT";
const USERS_ONLINE = "USERS_ONLINE";


export default {
    TOGGLE_IS_AUTH,
    DATA_USER,
    TOKEN,
    SET_EVENTS,
    IS_SUBMIT_CLICK,
    IS_CHANGE_USER_OPEN,
    IS_PHOTOREDACTOR_OPEN,
    SUBSCRIBE_EVENT,
    UN_SUBSCRIBE_EVENT,
    USERS_ONLINE,
}
